version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: quorum_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-quorum}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-quorum}
      POSTGRES_DB: ${POSTGRES_DB:-quorum}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-quorum}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: quorum_redis
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfilename "redis-data.aof"
      --requirepass ${REDIS_PASSWORD:-quorum}
    environment:
      REDIS_REPLICATION_MODE: master
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-quorum} ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local