services:
  redis:
    image: redis:7-alpine
    container_name: quorum_redis
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfilename "redis-data.aof"
      --requirepass ${REDIS_PASSWORD:-quorum}
    environment:
      REDIS_REPLICATION_MODE: master
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-quorum} ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quorum_backend
    env_file:
      - .env
    environment:
      # Override Redis URL to use Docker service name
      REDIS_URL: redis://:${REDIS_PASSWORD:-quorum}@redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quorum_frontend
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:8000
      - TOP_ORGANIZATIONS=compound,nounsdao,arbitrum
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
