services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quorum_app
    env_file:
      - .env
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:8716
    ports:
      - "8716:8716"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8716/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
