[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
dynamic_test_linking = true

# Gas reporting
gas_reports = ["*"]

# Fuzz testing configuration
[fuzz]
runs = 1000
max_test_rejects = 65536

# Invariant testing configuration  
[invariant]
runs = 256
depth = 15
fail_on_revert = false
show_metrics = true

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# RPC endpoints for deployment
[rpc_endpoints]
anvil = "http://localhost:8545"
base = "${BASE_RPC_URL}"

# Etherscan configuration
[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }