name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install test and lint dependencies
        run: uv pip install ruff==0.6.9 pytest # Pinned ruff version

      - name: Run Ruff Linter
        run: uv run ruff check --extend-select=ARG,T201,C90 .

      - name: Run Ruff Formatter Check
        run: uv run ruff format --check .

      - name: Run Pytest
        run: uv run pytest tests/
